check/frontend/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


#TODO validate register id is in form register:key and register is
# one we know about

class CheckForm(Form):
    register_id = StringField('Register ID', validators=[DataRequired()])

check/__init__.py
import os
from check.factory import create_app
app = create_app(os.environ['SETTINGS'])

check/frontend/views.py
from flask import (
    Blueprint,
    render_template,
    request,
    current_app,
    flash,
    abort,
    redirect,
    url_for
)

import requests

from check.frontend.forms import CheckForm

headers = {'Content-Type': 'application/json'}

frontend = Blueprint('frontend', __name__, template_folder='templates')


@frontend.route('/', methods=['GET', 'POST'])
def index():
    form = CheckForm()
    if form.validate_on_submit():
        register_id = form.data['register_id'].strip().lower()
        try:
            register, key = register_id.split(':')
            return redirect(url_for('frontend.check', register=register, key=key))
        except Exception as e:
            message = "There was a problem checking the %s register" % register_id
            flash(message)
            abort(500)
    return render_template('index.html', form=form)


@frontend.route('/check/<register>/<key>')
def check(register, key):
    try:
        url = _get_url(register, key)
        resp = requests.get(url, headers=headers)
        resp.raise_for_status()
        entry = resp.json()
        address = _get_address(entry)
        return render_template('check.html', entry=entry, address=address)
    except requests.exceptions.HTTPError as e:
        message = "We couldn't find a record for %s:%s" % (register, key)
        flash(message)
        if resp.status_code == 404:
            return render_template('check.html', register=register, key=key), 404
        abort(resp.status_code)
    except KeyError as e:
        message = "There was a problem checking the %s register with key %s" % (register, key)
        flash(message)
        abort(404)

    return redirect(url_for('.index'))


@frontend.route('/improve')
def improve():
    register = request.args.get('register')
    key = request.args.get('key')
    if not register and not key:
        abort(404)
    return render_template('improve.html', register=register, key=key)


def _get_url(register, key):
    config_name = register.replace('-', '_').upper()
    reg_url = current_app.config[config_name]
    url = '%s/%s/%s.json' % (reg_url, register, key)
    return url


def _get_address(entry):
    address_key = entry['entry']['address']
    address_register_url = current_app.config['ADDRESS_REGISTER']
    url = '%s/address/%s.json' % (address_register_url, address_key)
    try:
        resp = requests.get(url, headers=headers)
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        return None

config/__init__.py
from .config import Config
from .config import DevelopmentConfig
from .config import TestConfig

check/templates/401.html
{% extends "govuk_template.html" %}
{% block page_title %}Unauthorized{% endblock %}
{% block content %}
    <div>
        <h1>401</h1>
        <p>You are not authorized to see this page.</p>
    </div>
{% endblock %}

check/templates/check.html
{% extends "govuk_template.html" %}

{% block head %}
  <script src="https://maps.googleapis.com/maps/api/js"></script>
{% endblock %}

{% block content %}
  {% if entry %}
    <div class="grid-row">
      <div class="column-half">
          <h1 class="heading-large">{{entry.entry.name}}</h1>
          <p><img src="{{ asset_path }}images/ratings/rating-{{entry.entry.rating | lower | replace(' ','-')}}.png"/></p>
          <h2 class="heading-small">Date of rating</h2>
          <p>{{entry.entry['date-of-rating']}}</p>
          <h2 class="heading-small">Address</h2>
          <div class="address" itemscope itemtype="http://schema.org/PostalAddress">
            {% if address.entry.property %}
              <span>{{address.entry.property}}</span><br/>
            {% endif %}
            {% if address.entry.street %}
               <span itemprop="streetAddress">{{address.entry.street}}</span><br/>
            {% endif %}
            {% if address.entry.town %}
                <span itemprop="addressLocality">{{address.entry.town}}</span><br/>
            {% elif address.entry.locality %}
                <span itemprop="addressLocality">{{address.entry.locality}}</span><br/>
            {% elif address.entry.area %}
                <span itemprop="addressLocality">{{address.entry.area}}</span><br/>
            {% endif %}
            <span itemprop="postalCode">{{address.entry.postcode}}</span><br/>
            <span itemprop="addressCountry">{{address.entry['country']}}</span>
          </div>
      </div>
      <div class="column-half">
        <div id="map-canvas"></div>
        </div>
      </div>
      <div class="grid-row">
        <div class="column-half" id="check-another">
          <a href="{{url_for('frontend.index')}}" class="button">Check another licence or certificate</a>
          </div>
      </div>
      <div class="grid-row">
            <div class="column-half origin-panel">This page uses data from the <a href="http://food-hygiene.openregister.org/hash/{{entry.hash}}">Food Hygiene Register</a>
            </div>
      </div>
    {% else %}
      <div class="grid-row">
        <div class="column-two-thirds">
           <ul>
            <li>If you think this is wrong you can <a href="{{url_for('frontend.improve', register=register, key=key)}}">help us improve our records</a>.</li>
            <li>If you think you made a mistake go back and <a href="{{url_for('frontend.index')}}">check another licence or certificate</a>.</li>
          </ul>
        </div>
      </div>
    {% endif %}

{% endblock %}

{% block body_end %}
 {% if entry %}
  <script>
      var initialize = function () {
          var mapCanvas = document.getElementById('map-canvas'),
              coordinates = new google.maps.LatLng({{ address.entry.latitude }}, {{ address.entry.longitude }}),
              mapOptions = {
                  center: coordinates,
                  zoom: 15,
                  mapTypeId: google.maps.MapTypeId.ROADMAP,
                  zoomControl: true,
                  zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.SMALL
                  }
              },
              map = new google.maps.Map(mapCanvas, mapOptions),
              marker = new google.maps.Marker({
                  position: coordinates,
                  map: map,
                  title: "{{ entry.entry.name }}"
              });
      };

      $(document).ready(function(){
          initialize();
      });

  </script>
{% endif %}
{% endblock %}

check/templates/govuk_template.html
{% block top_of_page %}{% endblock %}
<!DOCTYPE html>
<!--[if lt IE 9]><html class="lte-ie8" lang="{{ html_lang|default('en') }}"><![endif]-->
<!--[if gt IE 8]><!--><html lang="{{ html_lang|default('en') }}"><!--<![endif]-->
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

    <title>{% block page_title %}GOV.UK - The best place to find government services and information{% endblock %}</title>

    <script type="text/javascript">
      (function(){if(navigator.userAgent.match(/IEMobile\/10\.0/)){var d=document,c="appendChild",a=d.createElement("style");a[c](d.createTextNode("@-ms-viewport{width:auto!important}"));d.getElementsByTagName("head")[0][c](a);}})();
    </script>

    <!--[if gt IE 8]><!--><link href="{{ asset_path }}stylesheets/govuk-template.css?0.13.0" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
    <!--[if IE 6]><link href="{{ asset_path }}stylesheets/govuk-template-ie6.css?0.13.0" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="{{ asset_path }}stylesheets/govuk-template-ie7.css?0.13.0" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="{{ asset_path }}stylesheets/govuk-template-ie8.css?0.13.0" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

    <link href="{{ asset_path }}stylesheets/govuk-template-print.css?0.13.0" media="print" rel="stylesheet" type="text/css" />

    <!--[if IE 8]>
    <script type="text/javascript">
      (function(){if(window.opera){return;}
       setTimeout(function(){var a=document,g,b={families:(g=
       ["nta"]),urls:["{{ asset_path }}stylesheets/fonts-ie8.css?0.13.0"]},
       c="{{ asset_path }}javascripts/vendor/goog/webfont-debug.js?0.13.0",d="script",
       e=a.createElement(d),f=a.getElementsByTagName(d)[0],h=g.length;WebFontConfig
       ={custom:b},e.src=c,f.parentNode.insertBefore(e,f);for(;h=h-1;a.documentElement
       .className+=' wf-'+g[h].replace(/\s/g,'').toLowerCase()+'-n4-loading');},0)
      })()
    </script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
      <link href="{{ asset_path }}stylesheets/fonts.css?0.13.0" media="all" rel="stylesheet" type="text/css" />
    <!--<![endif]-->


    <!--[if lt IE 9]>
      <script src="{{ asset_path }}javascripts/ie.js?0.13.0" type="text/javascript"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{{ asset_path }}images/favicon.ico?0.13.0" type="image/x-icon" />

    <!-- Size for iPad and iPad mini (high resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{{ asset_path }}images/apple-touch-icon-152x152.png?0.13.0">
    <!-- Size for iPhone and iPod touch (high resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="{{ asset_path }}images/apple-touch-icon-120x120.png?0.13.0">
    <!-- Size for iPad 2 and iPad mini (standard resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="{{ asset_path }}images/apple-touch-icon-76x76.png?0.13.0">
    <!-- Default non-defined size, also used for Android 2.1+ devices -->
    <link rel="apple-touch-icon-precomposed" href="{{ asset_path }}images/apple-touch-icon-60x60.png?0.13.0">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="{{ asset_path }}images/opengraph-image.png?0.13.0">

    <!-- gov uk elements stylesheet -->
    <link rel="stylesheet" type="text/css" href="{{asset_path}}stylesheets/main.css">

    <script type="text/javascript" src="{{asset_path}}javascripts/vendor/jquery/jquery.js"></script>

    {% block head %}{% endblock %}
  </head>

  <body class="{% block body_classes %}{% endblock %}">
    <script type="text/javascript">document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    {% block body_start %}{% endblock %}

    <div id="skiplink-container">
      <div>
        <a href="#content" class="skiplink">{{ skip_link_message|default('Skip to main content') }}</a>
      </div>
    </div>

    <div id="global-cookie-message">

        {% block cookie_message %}{% endblock %}

    </div>
    <!--end global-cookie-message-->

    <header role="banner" id="global-header" class="{% block header_class %}{% endblock %}">
      <div class="header-wrapper">
        <div class="header-global">
          <div class="header-logo">
            <a href="{{ homepage_url|default('https://www.gov.uk') }}" title="{{ logo_link_title|default('Go to the GOV.UK homepage') }}" id="logo" class="content">
              <img src="{{ asset_path }}images/gov.uk_logotype_crown.png?0.13.0" width="35" height="31" alt=""> {{ global_header_text|default('GOV.UK') }}
            </a>
          </div>
          {% block inside_header %}{% endblock %}
        </div>
        {% block proposition_header %}{% endblock %}
      </div>
    </header>
    <!--end header-->


    <div id="global-header-bar"></div>
    <!--end global-header-bar-->

    {% block after_header %}{% endblock %}



    <main id="wrapper" role="main">
      <div id="content">
        <div class="inner-block">
          <div class="phase-banner">
            <p>
              <strong class="phase-tag">ALPHA</strong>
              <span>This is a prototype service</span>
            </p>
          </div>
        </div>


      {%- with messages = get_flashed_messages(with_categories=true) -%}
        {% if messages %}
          <div class="inner-block">
            <div class="error-summary" role="group" aria-labelledby="error-summary-heading-example-1" tabindex="-1">
              <ul class="error-summary-list flashes">
                {% for category, message in messages %}
                  <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endif %}
      {%- endwith %}

    {% block content %}{% endblock %}

    </div>
  </main>

    <footer class="group js-footer" id="footer" role="contentinfo">

      <div class="footer-wrapper">
        {% block footer_top %}{% endblock %}

        <div class="footer-meta">
          <div class="footer-meta-inner">
            {% block footer_support_links %}{% endblock %}

            <div class="open-government-licence">
              <p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>

                {% block licence_message %}<p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>{% endblock %}

            </div>
          </div>

          <div class="copyright">
            <a href="https://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm"><span>&copy;</span>{{ crown_copyright_message|default('Crown copyright') }}</a>
          </div>
        </div>
      </div>
    </footer>

    <!--end footer-->

    <div id="global-app-error" class="app-error hidden"></div>

    <script src="{{ asset_path }}javascripts/govuk-template.js?0.13.0" type="text/javascript"></script>

    {% block body_end %}{% endblock %}
  </body>
</html>

check/templates/improve.html
{% extends "govuk_template.html" %}

{% block head %}
  <script src="https://maps.googleapis.com/maps/api/js"></script>
{% endblock %}

{% block content %}

    <div class="grid-row">
      <div class="column-two-thirds">
        <h1 class="heading-large">Help us improve our records</h1>
        <h2 class="heading-small">We couldn't find a record for</h2>
        <p>{{register}}:{{key}}</p>

        <form id="improve">
          <div class="form-group">
            <label class="form-label-bold" for="message">If you think this is an error, please give us details</label>
            <span class="form-hint">For example, where you found this ID</span>
            <textarea id="message" rows="10" cols="50"></textarea>
          </div>
          <div class="form-group">
            <label class="form-label-bold" for="email">Your email</label>
            <span class="form-hint">If you would like to be kept up to date on this issue</span>
            <input class="form-control" id="email" type="email" />
          </div>
          <div class="form-group">
            <input type="submit" class="button" value="Submit" disabled="true"/>
          </div>
        </form>

      </div>
    </div>
{% endblock %}

check/templates/index.html
{% extends "govuk_template.html" %}

  {% block content %}
    <div class="grid-row">
      <div class="column-two-thirds">
        <div class="check">
          <h1 class="form-title heading-large">Check a licence or certificate</h1>
          <form class="form" action="{{url_for('frontend.index')}}" method="POST">
            <div class="form-group">
              <div class="{% if form.register_id.errors %}error{% endif %}">
                <label class="form-label-bold" for="register_id">Enter licence or certificate ID</label>
                <span class="form-hint">
                  This is normally a word and some numbers or letters, separated by a colon.
                  <br>
                    For example, food-hygiene:2764
                </span>
                {{ form.register_id(class_="form-control")|safe }}
                {% if form.register_id.errors %}
                  {% for error in form.register_id.errors %}
                    <span class="error">{{error}}</span>
                  {% endfor %}
                {% endif %}
              </div>
            </div>
            <div class="form-group">
              <input type="submit" class="button" value="Check">
            </div>
            {{ form.csrf_token }}
          </form>
        </div><!-- end .check -->
      </div>

      <div class="column-third">
        <div class="related-container">
          <div class="related">
            <h2 class="heading-medium">Registers</h2>
            <nav role="navigation" aria-labelledby="parent-subsection">
              <ul>
                <li><a href="http://www.openregister.org">About registers</a></li>
                <li><a href="http://register.openregister.org">Search for a register</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}